[build]
  publish = "public" # or the directory where your HTML files are located
  command = "" # leave this empty if you don't have a build command

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
